services:

  postgres:
    image: postgres:16
    container_name: price_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pricetracker

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data



  redis:
    image: redis:7
    container_name: price_redis

    ports:
      - "6379:6379"



  api:
    build:
      context: .

    container_name: price_api

    command:
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis



  worker:
    build:
      context: .

    container_name: price_worker

    command:
      celery
      -A app.worker.celery_app.celery
      worker
      --loglevel=info

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - postgres
      - redis



volumes:

  postgres_data: